// lib/recal.q — vol-adaptive recalibration runner (.recal.*).
//
// One run: pull the trailing window of ref-venue quotes from the live RDB, solve each asset's
// winreset bar for the target rate (lib/autocal.q), and — on apply — hot-push the new bars into the
// live bridge via IPC (the detector reads .cfg.threshold every batch, so it takes effect at once, no
// restart) and rewrite config/move_cal.q so a restart keeps them. Opens/closes its own RDB+bridge
// handles per run -> robust to stack restarts, and drivable either one-shot (sim/recal_live.q) or on
// a timer (proc/recal.q). Off the engine hot path: the heavy detector sweep runs in THIS process.
// Needs .cfg.canon/symCanon (proc/load.q), lib/movedetect.q, lib/autocal.q.

.recal.R        :24f;                       // target major-move rate (events/hr)
.recal.winMs    :500f;                      // detector window — MUST match .cfg.moveWinMs
.recal.basis    :`log;
.recal.windowHr :3f;                        // trailing data window
.recal.rdbPort  :5011;
.recal.bridgePort:5099;
.recal.refVenue :`BINANCE;
.recal.minTicks :5000;                      // per-asset data sufficiency (skip if below)
.recal.minSpanHr:0.5;
.recal.bounds   :0.1 100f;                  // sane bps bar bounds (skip if a solved bar lands outside)
.recal.cfgFile  :`:config/move_cal.q;

// build per-root series (t = exch_us ns in recv order, v = mid, medSpr) from a raw bookticker table.
.recal.series:{[bt]
  bt:select recv_us, exch_us, root:.cfg.canon sym, mid:0.5*bid+ask, sprBps:10000*(ask-bid)%0.5*bid+ask
     from bt where not null bid, not null ask, bid<ask, sym in key .cfg.symCanon;
  select t:1000*exch_us, v:mid, medSpr:med sprBps by root from `recv_us xasc bt};

// solve + gate one asset against its current bar -> a result row.
.recal.row:{[ser;cur;root]
  has:root in (key ser)`root;
  d:$[has; .autocal.calibrate[.recal.basis; `long$1e6*.recal.winMs; (ser root)`t; (ser root)`v; (ser root)`medSpr; .recal.R];
          `thrBps`unitBps`floored`ratePerHr`spanHr`nTicks!(0n;0n;0b;0n;0n;0)];
  c:cur root; c:$[null c; .cfg.moveThresholdDefault; c];
  status:$[not has;                                           `SKIP_NODATA;
           (d[`nTicks]<.recal.minTicks) or d[`spanHr]<.recal.minSpanHr; `SKIP_THIN;
           not (d[`thrBps] within .recal.bounds);             `SKIP_BOUNDS;
           d`floored;                                         `OK_FLOORED;   // quiet regime, bar at floor — still apply
                                                              `OK];
  `root`curBar`newBar`ratePerHr`floored`nTicks`spanHr`status!
    (root; c; d`thrBps; d`ratePerHr; d`floored; d`nTicks; d`spanHr; status)};

// rewrite config/move_cal.q with the merged bars (so a restart keeps them).
.recal.emit:{[newBars]
  hdr:(
    "// config/move_cal.q — per-asset move thresholds (consumed by lib/feed.q via .cfg.threshold).";
    "// GENERATED by lib/recal.q (sim/recal_live.q / proc/recal.q) — vol-adaptive rate-targeting; do not hand-edit.";
    "//   scheme : the bar is the bps that yields ~target events/hr on a trailing live window, floored at";
    "//            max(noise sigma, median spread). Re-solved hourly so it tracks volatility (rises hot,";
    "//            falls quiet). detector = winreset (B8), clock = exch_us; valid ONLY under winreset at";
    "//            .cfg.moveWinMs matching the calibration window (see DECISIONS B8).";
    ("// recalibrated ",string[.z.p]," from RDB :",string[.recal.rdbPort],
       " trailing ",string["j"$.recal.windowHr],"h — R*=",string["j"$.recal.R],"/hr, winreset win=",string["j"$.recal.winMs],"ms");
    (".cfg.moveThresholdBps:`",("`" sv string key newBars),"!",(" " sv .Q.f[3] each value newBars),";"));
  .recal.cfgFile 0: hdr;
  -1 "  rewrote ",1_string .recal.cfgFile;};

// one recalibration pass. apply=0b -> dry-run (print diff only); 1b -> push to bridge + rewrite config.
// Returns the per-asset result table. No exit (safe to call on a timer).
.recal.run:{[apply]
  -1 "\n=== recal ",string[.z.p]," ",$[apply;"(APPLY)";"(DRY-RUN)"]," — R*=",string[.recal.R],"/hr, window=",.Q.f[2;.recal.windowHr],"h ===";
  // --- pull trailing window from the RDB ---
  hR:@[hopen; .recal.rdbPort; 0Ni];
  if[null hR; -1 "  RDB :",string[.recal.rdbPort]," unreachable — skipping this run."; :()];
  mx:hR({[v] exec max recv_us from bookticker where venue=v}; .recal.refVenue);
  cutoff:mx - `long$.recal.windowHr*3.6e9;                    // us window (1 hr = 3.6e9 us)
  bt:hR({[v;c] select recv_us,exch_us,sym,bid,ask from bookticker where venue=v, recv_us>=c}; .recal.refVenue; cutoff);
  hclose hR;
  ser:.recal.series bt;
  -1 "  pulled ",string[count bt]," ref-venue ticks over trailing ",.Q.f[2;.recal.windowHr],"h (",string[count ser]," assets).";
  // --- current LIVE bars (bridge), fallback to on-disk ---
  cur:.cfg.moveThresholdBps;
  hB:@[hopen; .recal.bridgePort; 0Ni];
  $[null hB; -1 "  (bridge :",string[.recal.bridgePort]," unreachable — diffing vs on-disk bars)";
    [cur:hB".cfg.moveThresholdBps"; hclose hB]];
  syms:asc distinct (key cur),(key ser)`root;
  res:.recal.row[ser;cur] each syms;
  show res;
  ok:select root, newBar from res where status in `OK`OK_FLOORED;
  if[not count ok; -1 "  no assets cleared the gates — nothing to apply."; :res];
  newBars:cur,(exec root from ok)!exec newBar from ok;        // upsert OK bars over current
  if[not apply; -1 "  DRY-RUN: nothing pushed."; :res];
  // --- APPLY ---
  @[{[x] h:hopen .recal.bridgePort; h(set;`.cfg.moveThresholdBps; x); hclose h;
     -1 "  pushed ",string[count x]," bar(s) to live bridge :",string .recal.bridgePort};
    newBars; {[e] -1 "  WARN bridge push failed (",e,") — config still rewritten for next restart."}];
  .recal.emit newBars;
  res};
