// config/move_cal.q — per-asset quote-clock move thresholds (consumed by lib/feed.q via
// .cfg.threshold -> .cfg.moveThresholdBps).
//
// In production these are GENERATED by lib/recal.q (vol-adaptive rate-targeting): the bar is
// the bps that yields ~target events/hr on a trailing live window, re-solved periodically so it
// tracks volatility. The values below are NEUTRAL PLACEHOLDERS so the engine loads and runs
// out of the box — regenerate them against your own market data with the recal tooling.
// Unlisted symbols fall back to .cfg.moveThresholdDefault (config/params.q).
.cfg.moveThresholdBps:`BTC`DOGE`ETH`SOL`XRP!3 4 5 4 4f;
